#! /bin/bash
#===============================================================================
# Copyright 2020 FUJITSU LIMITED
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================
export TCSDS_PATH="/opt/FJSVstclanga/v1.1.0"
export PATH=${TCSDS_PATH}/bin:$PATH
export LD_LIBRARY_PATH="${TCSDS_PATH}/lib64:${LD_LIBRARY_PATH}"

export CC="fcc -Nclang -Kfast -Knolargepage -Kopenmp -Nlibomp"
export CXX="FCC -Nclang -Kfast -Knolargepage -Kopenmp -Nlibomp"
